### ISSUE TITLE
Kobo Glo - no usb connection

### ISSUE THREAD

**Issue by lucdoebereiner** [Kobo-InkBox/inkbox#10]
Hi, thank you so much for this incredible project!!

I have an issue with the usb connection. I run 1.5. (fleshly installed) and my Glo starts and runs well, but if I connect it via USB I'm not able to mount it. I actually don't see it at all (in fdsik, e.g.) I'm running debian and I tried it on two systems (also with 2 different usb cables). Is there a way I could help debugging this?

**Comment by lucdoebereiner** [comment]
No, none

**Comment by tux-linux** [comment]
Did you try to reboot the Kobo to be certain?

**Comment by tux-linux** [comment]
Maybe are you trying with two USB power-only cables?

**Comment by lucdoebereiner** [comment]
Yes, I say "connect" and nothing happens.

In the meantime, I tried updating in the hope that would perhaps fix it. I managed to mount the onboard file (taking out the sd card) I copied the 1.8 update into the respective directory. It updated but now I get "InkBox crash, Error Code: 3" everytime I start.

**Comment by lucdoebereiner** [comment]
Btw. I have the 2 gb n613, so I had to use another sd card as the image is 3.6 gb. Could that be the reason?

**Comment by tux-linux** [comment]
> Yes, it says "connect" and nothing happens.
> 
> In the meantime, I tried updating in the hope that would perhaps fix it. I managed to mount the onboard file (taking out the sd card) I copied the 1.8 update into the respective directory. It updated but now I get "InkBox crash, Error Code: 3" everytime I start.

https://www.mobileread.com/forums/showthread.php?t=337972
Please read the "Important" part in the main post. There was a change between 1.5 and 1.6 regarding rootfs verification, so you need to update to 1.6 first.
This should fix it:
```
# mount /dev/mmcblk0p3 /mnt
# mount inkbox-update-1.8.upd.isa /mnt1
# cp /mnt1/rootfs.squashfs.dgst /mnt/rootfs.squashfs.dgst
# sync
# umount /mnt /mnt1
```

**Comment by tux-linux** [comment]
> Btw. I have the 2 gb n613, so I had to use another sd card as the image is 3.6 gb. Could that be the reason?

Nope, at this point it might be a hardware problem, I mean, if there aren't any ring buffer messages about just an USB port activated or a new device detected, I don't really know how to fix that problem.
Maybe you could connect your device via serial port and we could try to diagnose the issue further.

**Comment by tux-linux** [comment]
I don't know what to tell you, I have a Glo too and I don't experience this problem at all.
External SD card is not supported as of now.
For now, it's cumbersome, but you could mount the `onboard` file and add books there, they'll be accessible from the GUI.

**Comment by lucdoebereiner** [comment]
That's what I'll do. Thanks!
