### ISSUE TITLE
Glo - Resolution on Home Screen 1.8

### ISSUE THREAD

**Issue by lucdoebereiner** [Kobo-InkBox/inkbox#11]
Hi (again),

I'm on 1.8. now. It mostly works fine, but only half of the home screen is displayed, i.e. the resolution seems twice as high as what the display can show (and landscape instead of portrait), so that the vertical height is ok but the horizontally half is cut. Opening a book, file browser etc. are all displayed correctly.

**Comment by tux-linux** [comment]
Do you have a screenshot?
Your Kobo's starting to scare me ;p

**Comment by tux-linux** [comment]
Mine seems to be fine...
![PXL_20220114_155247762.jpg](https://user-images.githubusercontent.com/63172576/149544935-0b043845-e793-4706-81b3-a9b4b4f7113b.jpg)

**Comment by lucdoebereiner** [comment]
: )
Here it is:
![IMG_20220114_185214685_HDR](https://user-images.githubusercontent.com/10145334/149562503-283d7c3a-1efb-49ae-a5a2-1caf22b3f08b.jpg)

**Comment by tux-linux** [comment]
Oh, that's because of the book names' length. I'm planning on fixing that soon.
For now, you can 1) Rename your books to a shorter name, and 2) :
```
# mount /dev/mmcblk0p4 /mnt
# rm -f /mnt/config/08-recent_books/*
# umount /mnt
# sync
```

**Comment by lucdoebereiner** [comment]
Thanks! Good to know it behaves as expected :)
