### ISSUE TITLE
[Kobo Glo N613][Version: 1.8] Scalling problem

### ISSUE THREAD

**Issue by mengpo1** [Kobo-InkBox/inkbox#13]
Hi there,

I've got a strange problem when using the Inkbox. When I opened an ebook (whichever type) for the first time using the OS and I try to go back to home, the UI is bit too zoomed. And even if I disable the UI scalling in the settings or if I try to zoom out via this option, the UI cannot be zoomed out. Worse, if I try to zoom in, it stays this way. Resetting the device is my only option now.

Thanks,

Edit : the UI is not zoomed in inside the settings. It is in Home (I cannot see the reboot button) and when opening an ebook.

**Comment by mengpo1** [comment]
Edit : the UI is not zoomed in inside the settings. It is in Home and when opening an ebook

**Comment by tux-linux** [comment]
Hello, is your issue similar to #11?
In this case, it's fixed and will not happen in the next release.

**Comment by mengpo1** [comment]
Oh come on ! I forgot to remove the issue filters. 

Sorry, yes it's exactly the same problem...
