### ISSUE TITLE
[Kobo Glo N613][Version: 1.8]Cannot exit Light Maps

### ISSUE THREAD

**Issue by mengpo1** [Kobo-InkBox/inkbox#15]
Hi there,

When I'm opening the application Light Maps, I only go the Options menu (which shows only Oslo, Berlin, Jakarta, Night Mode and About OpenStreetMap) and I cannot exit the application. I can only soft reboot the kobo. Maybe, I missed something here ;)

For the rest, I think that no map is displayed because the N613 doesn't have the wifi...

**Comment by tux-linux** [comment]
Hello,
Yeah, no maps are displayed because the Glo doesn't have Wi-Fi.
There's currently no way to exit it either... Maybe I could fix that for 1.9.
Thanks for reporting.

**Comment by mengpo1** [comment]
Maybe the easiest way is to hide this app ? (just a suggestion)

**Comment by tux-linux** [comment]
Yeah, nice suggestion.
It's worthless without Wi-Fi access.
