### ISSUE TITLE
Support for Kobo Glo HD

### ISSUE THREAD

**Issue by andreas5232** [Kobo-InkBox/inkbox#16]
I'm currently trying to get a used Kobo and repurpose it as an energy efficient clock and smart home dashboard.

Is there any chance to get inkbox running on the Glo HD?

In case I'm lucky to get one, I can of course help with debugging and testing! :)

**Comment by andreas5232** [comment]
Unfortunately there haven't been any other used  devices than the Glo and the Glo HD for sale in the cheaper price range. At least when looking for Germany. In case everything works out as expected, I'd probably it by a more recent/powerful Kobo later. 

Anyway I'm really glad to hear that the Glo HD will be supported soon, as I've just received the order confirmation and will probably have it here within the next few days.

In case there is any beta release for the Glo HD please let me know.

Regarding the panics: I haven't developed any kernel stuff yet, but I'll definitely try to get them sorted out.

I'm really looking forward to being part of the Kobox/InkboxOS community soon! 😊

**Comment by andreas5232** [comment]
Woohoo... We'll that was quick! I've just received the Kobo Glo HD I bought yesterday 😊

Is there any InkBox related stuff that I can test with yet?

Otherwise I'd probably try getting started with Alpine Linux myself by using this little wiki how-to: https://wiki.mobileread.com/wiki/Create_a_Native_Development_Environment_on_Kobo

Cheers
Andreas

**Comment by tux-linux** [comment]
Hello, not much yet.
I have good news though: with a newer Qt platform plugin, the kernel doesn't seem to panic/trace anymore. Which adds a lot to the stability of InkBox.
1.9 release should come soon. I'll sure let you know when it does!

**Comment by tux-linux** [comment]
InkBox 1.9 is out!
http://23.163.0.39/bundles/inkbox/native/n437/inkbox-1.9-n437.xz
