### ISSUE TITLE
Screen Resolution Bug & Why not add Koreader instead of mupdf??

### ISSUE THREAD

**Issue by Azarel67** [Kobo-InkBox/inkbox#17]
Hi, I wanna say I love this project of yours. However if you don't mind me asking, since koreader is also open source, why not add that in the OS instead of mupdf??

I love the OS overall and it's a great concept, the one thing that's bugging me is the buttons on the bottom while reading books. I'd prefer a clean reading experience like koreader.

**Comment by tux-linux** [comment]
Hello,

The concept of InkBox was to build it from scratch, not by taking inside another complete ecosystem. Also, AFAIK, KOReader isn't that scalable. InkBox uses Qt in the entire GUI and is completely integrated.
I don't know how you can fit KOReader in there in a seamless way and maintaining support for all config options found in `/opt/config/`.
And the purpose of InkBox is not to become a KOReader bridge. It was never intended like that.

Thank you and have a good day!

**Comment by NiLuJe** [comment]
Also, fun fact: KOReader also uses MµPDF for PDF rendering ;o).

**Comment by Azarel67** [comment]
Don't get me wrong, the OS itself is great, I just like having custom screensavers and whatnot. Haha. That's me nitpicking at this stage.

Anyhow I installed it on my kobo  to test it out and I'm having an issue with not being able to open any documents, the file manager is much larger than the screen, the open button extends to the right side beyond the screen and I'm not able to press it, is this a bug???

Model: Kobo C905
Version: v1.8

Lemme know if you need any more details.

I didn't know that Niluje. But still I prefer koreader for its customizations. Haha.

**Comment by Azarel67** [comment]
Ah damn, that's too bad, I do like this OS. Lemme see if I can fix it, if I do, I'll let you know. Thanks for everything.
