### ISSUE TITLE
Porting InkBox for kobo nia

### ISSUE THREAD

**Issue by Szybet** [Kobo-InkBox/inkbox#18]
Hello
InkBox seems like a interesting project, I own a kobo nia and I want to port it to it.
I also hope the side effect of that will be to [solve my issue](https://github.com/kobolabs/Kobo-Reader/issues/116)

I already [compiled the kernel](https://github.com/Szybet/kobo-nia-audio/tree/main/kernels/oryginal) for the kobo nia, so adding InkBox should be easy

**Comment by tux-linux** [comment]
WIP!
For folks who want to know how it's done, check out the Kobo Nia porting thread in InkBox Discord.

**Comment by Szybet** [comment]
Discord is described in the dev community as a knowledge black hole, so here is the chat exported:
[The *Box Project - porting - Kobo Nia (N306).zip](https://github.com/Kobo-InkBox/inkbox/files/8103799/The.Box.Project.-.porting.-.Kobo.Nia.N306.zip)

In the future I will make a step by step guide and post it in my repository, and on the inkbox wiki

**Comment by Szybet** [comment]
[The *Box Project - porting - Kobo Nia (N306).zip](https://github.com/Kobo-InkBox/inkbox/files/8237718/The.Box.Project.-.porting.-.Kobo.Nia.N306.zip)

Done, everything works
