### ISSUE TITLE
[bug] Authors quote appearing in various situtations

### ISSUE THREAD

**Issue by Szybet** [Kobo-InkBox/inkbox#21]
Image of the bug:
![IMG_20220322_222906](https://user-images.githubusercontent.com/53944559/159580121-fbda465d-4343-47ea-b616-09c62dd22434.jpg)

Most often when canceling file chooser. In my opinion Global reading settings doesn't affect this. I have disabled authors quotes in settings

**Comment by tux-linux** [comment]
Duplicate of #19.
