### ISSUE TITLE
Installation issues with Kobo Touch N905C

### ISSUE THREAD

**Issue by thatHguy** [Kobo-InkBox/inkbox#26]
I've been trying to install Inkbox on an N905C, but upon flashing BalenaEtcher warns that the device memory is 2gb, and the Inkbox image from the pre-compiled downloads requires 3.87gb. Tried to flash to external sd card with adequate space, but the device doesn't boot into Inkbox.

How did other people install Inkbox onto their Kobo Touch with only 2gb internal storage? The [wiki also says](https://inkbox.ddns.net/wiki/index.php?title=Main_Page) that devices need at least 4gb of storage.

**Comment by tux-linux** [comment]
Hello, you can't install InkBox on an SD card with less than 4G of capacity.
Just put your 4G one inside the Kobo, not as an external one. Swap it with the 2G one, in other words.
