### ISSUE TITLE
How to access Diagnostics Mode on a Kobo Glo HD?

### ISSUE THREAD

**Issue by QueasyQolon** [Kobo-InkBox/inkbox#30]
I might be missing something, but I have no idea how to enter diagnostics mode on the aforementioned model. On the Mini, there's a dedicated slide switch, but the Glo HD only has the one button.

Help?

**Comment by tux-linux** [comment]
Hello, you have to press the main button repeatedly as soon as it starts blinking. Then, you may wait ~30-40 seconds for the Diagnostics mode to start.
