### ISSUE TITLE
Kobo Libra H2O Support

### ISSUE THREAD

**Issue by aboss10123** [Kobo-InkBox/inkbox#35]
Hi, I have a kobo libra h2O and I would like to help out in getting inkbox to be ported on this machine. I don't know if there is a removable sd card inside (its probably soldered in). However, I tried flashing one of the other pre compiled binaries just to see what will happen but the kobo device itself just idk somehow fixed itself and did a factory reset. If you don't plan on supporting this device, I would like to swap their inkbox capable device with my libra h2O haha (you guys probably won't seeing as this project is really that amazing).

Kind regards

**Comment by tux-linux** [comment]
Hello, we already provide unofficial support for it, because installing InkBox OS on it is really something, you can join the Discord server for more info : https://discord.com/invite/uSWtWbY23m
