### ISSUE TITLE
Support for Kobo Touch N905 (internal Emmc)?

### ISSUE THREAD

**Issue by emulti** [Kobo-InkBox/inkbox#43]
Would it be possible to add support in this interesting project for the original Kobo Touch N905?
This is the model with internal 2GB Emmc and an external SD card slot. It has an Atheros AR6003 wifi chip which is supported by the ath6kl driver in modern kernels but it's running 2.6.35. At the time of release this was a 'staging' driver (compiled module ar6000.ko) but I haven't found the sources. 
Wifi doesn't work with the stock OS (as far as I can tell) with various versions, which makes it very difficult to debug as usb networking isn't available either. 
I believe it's possible to boot from the external SD slot when holding the 'home' button during power-on.

**Comment by Szybet** [comment]
Is it possible? _yes_.
Is there someone willing to do it? If not you then no one. Of course we are happy to help you

**Comment by emulti** [comment]
Good to know there are no technical blocking issues!
I am willing to have a try within the limits of my technical knowledge. 
I have made an image of the internal storage and have examined the unpartitioned space. It doesn't seem to have a HW CONFIG block- the $PLATFORM is the default, 'freescale'. Wifi seems to use the old 'wext' framework of the kernel. 
As a first step I will try and compile a kernel and see if I can boot from it on the external microSD slot.

**Comment by Szybet** [comment]
There are technical issues, but we need to solve them.
Let's continue the conversation on discord

**Comment by Szybet** [comment]
Read the readme...
