### ISSUE TITLE
Kobo Nia: diagnostics mode on installation 

### ISSUE THREAD

**Issue by mu88** [Kobo-InkBox/inkbox#47]
Hi 👋🏻

I've flashed the storage of my Kobo Nia, everything worked smoothly. When turning the device on for the first time and since then, I always end up in _inkbox Diagnostics and Recovery_ - it never booted "normally".

How can I exit this loop?

**Comment by Szybet** [comment]
https://web.archive.org/web/20230323191406/https://inkbox.ddns.net/wiki/index.php?title=Basic_diagnostics_kernel

this? it's not supported... and never tested, how? @tux-linux 
this is propably a bigger issue, please join discord / matrix to figure out to fix it

**Comment by tux-linux** [comment]
Take a screen shot of the "Flags" tab in this program and send it please.
Also I'm starting to realize we pretty much only encounter Nia inkbox
users, quite funny @Szybet

**Comment by Szybet** [comment]
Yea, I wonder why

**Comment by mu88** [comment]
Because it's listed here... https://inkbox.ddns.net/downloads.html

**Comment by mu88** [comment]
![Uploading IMG_20230422_201627.jpg…]()

**Comment by mu88** [comment]
![IMG_20230422_201627](https://user-images.githubusercontent.com/4560672/233800304-d35bfc4a-63fa-46e6-afa8-6be3a622f0b5.jpg)

@tux-linux here you go

**Comment by tux-linux** [comment]
Please try to check, then uncheck `Always boot to recovery` and reboot it.

**Comment by mu88** [comment]
I've checked, unchecked, rebooted and now it is stuck in _Rebooting_ for the last hour

![IMG_20230422_224748](https://user-images.githubusercontent.com/4560672/233806027-31fa2cb3-879b-4904-ac49-d67653f988df.jpg)

When holding the power button pressed for ten seconds, I'm back in recovery mode.

**Comment by Szybet** [comment]
@tux-linux how is it even possible? Nia doesn't have a second button to enter this mode during boot?

**Comment by tux-linux** [comment]
> @tux-linux how is it even possible? Nia doesn't have a second button to enter this mode during boot?

You can enter this mode by pressing the power button repeatedly or just holding it in this case. The BDK is for other devices which have a secondary button. This boots a basic GUI using FBInk with serial-only user interaction to perform first-necessity recovery operations.
This particular recovery mode is made with Qt components and allows for a broader range of recovery operations, and you can also rescue your system by flashing, say, a new rootfs via USBNet more easily than with the BDK.

**Comment by tux-linux** [comment]
> I've checked, unchecked, rebooted and now it is stuck in _Rebooting_ for the last hour
> 
> ![IMG_20230422_224748](https://user-images.githubusercontent.com/4560672/233806027-31fa2cb3-879b-4904-ac49-d67653f988df.jpg)
> 
> When holding the power button pressed for ten seconds, I'm back in recovery mode.

Try to reflash the image to the SD card, `sync` three times and report back.
--- or ---
Connect it via serial port and we can try to figure out what's wrong...
--- or ---
Enable `DISPLAY_DEBUG` (in Flags tab) and take a screenshot of what's happening at boot.

**Comment by mu88** [comment]
> Enable DISPLAY_DEBUG (in Flags tab) and take a screenshot of what's happening at boot.

Nothing happens when enabling this option - on reboot, the display only shows _Rebooting_

> Try to reflash the image to the SD card, **sync three times** and report back.

How do I sync?

**Comment by Szybet** [comment]
`sync` linux command
If you are on windows then format the sd card ( completly ) and flash it again, then unmount it safely

**Comment by mu88** [comment]
After reflashing on Windows, the problem remains the same: after holding and releasing the power button for three seconds and waiting five minutes, nothing happens. After holding and releasing the power button for ten seconds, the Kobo enters diagnostics mode.

So I tried it with my Raspi, but still without success. Here's what I did:
- Copy downloaded firmware from Windows to Linux via `scp -r scp -r .\inkbox-1.9-n306.xz myUser@myRaspi:/home/myUser/temp
- Detect MicroSD card via `sudo fdisk l`→ `/dev/sdb`
- Format MicroSD and install:  
```
sudo su
mkfs -t ext2 /dev/sdb
xzcat inkbox-1.9-n306.xz | dd of=/dev/sdb status=progress
```
The problem is still the same, the Kobo end up in diagnostics mode.

**Comment by Szybet** [comment]
well the only option i see now is to connect a serial port to the ereader, could you do it?

**Comment by mu88** [comment]
With a manual/guidance I can give it a try, sure

**Comment by Szybet** [comment]
Could you join discord / matrix server? it would be faster to explain than here

**Comment by mu88** [comment]
Now at least the `DISPLAY_DEBUG` seems to work 

![IMG_20230423_125250](https://user-images.githubusercontent.com/4560672/233835621-d0bfc906-ab30-4b9c-9ccd-2f5b98d1f9ff.jpg)
![IMG_20230423_125149](https://user-images.githubusercontent.com/4560672/233835623-c3782df4-90ed-4d5e-a356-b6da5f2b21b9.jpg)

**Comment by tux-linux** [comment]
> Now at least the `DISPLAY_DEBUG` seems to work 
> 
> ![IMG_20230423_125250](https://user-images.githubusercontent.com/4560672/233835621-d0bfc906-ab30-4b9c-9ccd-2f5b98d1f9ff.jpg)
> ![IMG_20230423_125149](https://user-images.githubusercontent.com/4560672/233835623-c3782df4-90ed-4d5e-a356-b6da5f2b21b9.jpg)
> 

You seem to have a power button stuck in place, or something else producing an unwanted input event in your hardware. It's really strange

**Comment by mu88** [comment]
![IMG_20230423_130116](https://user-images.githubusercontent.com/4560672/233836038-89dd4f3e-3ece-4270-8bd2-63644f74a13d.jpg)

**Comment by mu88** [comment]
![IMG_20230423_130951](https://user-images.githubusercontent.com/4560672/233836402-273af486-4056-48b6-af43-2a8b0435b0ae.jpg)
![IMG_20230423_130957](https://user-images.githubusercontent.com/4560672/233836404-a7ed4169-9b8a-4b93-aa17-a59a14eb7e48.jpg)
![IMG_20230423_131014](https://user-images.githubusercontent.com/4560672/233836407-3027e001-216e-4e26-a69c-7a46b006b961.jpg)
![IMG_20230423_131021](https://user-images.githubusercontent.com/4560672/233836409-e58f4f9a-e5bb-41a4-aea3-67d2e01f2e62.jpg)
![IMG_20230423_131026](https://user-images.githubusercontent.com/4560672/233836410-8bd513ac-95a4-4148-b574-20b90a35fc2d.jpg)

**Comment by tux-linux** [comment]
New Nia hardware...
(Reporting back from Discord)

**Comment by mu88** [comment]
![IMG_20230423_131404](https://user-images.githubusercontent.com/4560672/233836576-37a00db3-ca90-40ad-97c9-efa2344e8923.jpg)
![IMG_20230423_131407](https://user-images.githubusercontent.com/4560672/233836577-5d33c514-19c6-4ac1-9643-479dc2a99df2.jpg)

**Comment by Szybet** [comment]
![img4](https://user-images.githubusercontent.com/53944559/233836546-673b874e-ca04-4233-8278-210dfb0a92b0.jpg)

for context, the original ( charging IC changed, crystal oscilator next to cpu, a new 3 pin IC on the bottom, and propably another PCb manufacturer )

**Comment by Szybet** [comment]
at least the bottom is the same

**Comment by Szybet** [comment]
also a diffrent battery ( chinesium )...

**Comment by Szybet** [comment]
Ok, the top of the PCB has a serial number, me and Kuratius have 4A2 and mu88 has 4C1
# where is B?...

**Comment by mu88** [comment]
![IMG_20230423_134848](https://user-images.githubusercontent.com/4560672/233837958-d30b622c-0948-4e34-86ac-c3eb190a24f6.jpg)
![IMG_20230423_134832](https://user-images.githubusercontent.com/4560672/233837960-00fff527-0fda-41ac-9abd-afab7c897499.jpg)

**Comment by mu88** [comment]
![IMG_20230423_135236](https://user-images.githubusercontent.com/4560672/233838102-c58902b7-ae54-49f3-a68c-9b019be45cd5.jpg)

**Comment by mu88** [comment]
![IMG_20230423_135939](https://user-images.githubusercontent.com/4560672/233838437-c6985553-a58f-41e3-8554-065abd8ddf0e.jpg)
![IMG_20230423_135934](https://user-images.githubusercontent.com/4560672/233838438-6e9375a8-61c9-4c26-a728-d337f0e2286c.jpg)

**Comment by mu88** [comment]
![IMG_20230423_140044](https://user-images.githubusercontent.com/4560672/233838483-cc7764c9-7f4d-476e-9735-ab6693dcb9b3.jpg)
![IMG_20230423_135939](https://user-images.githubusercontent.com/4560672/233838484-be627c8f-af8d-411c-acf6-083e84ec3bb9.jpg)

**Comment by Szybet** [comment]
Maybe soon ( I got access to another Nia, maybe it's the C variant, haven't checked yet ).
Anyway, we are waiting for you to return to port InkBox to it

**Comment by mu88** [comment]
Sounds good 👍🏻 well I'm back and can try to assist you. Do we need another "interactive session" like on the weekend before my vacation? If yes, I can try to devote one or two hours on the weekend to it.

Otherwise, if we could do it asynchronously I'll see what I can do

**Comment by Szybet** [comment]
As of me I won't have time on this weekend
yep, asynchronously is the best way to go

**Comment by mu88** [comment]
Okay, so just leave me a comment here about what I shall do

**Comment by Szybet** [comment]
Go on discord to make it faster ;p

**Comment by KitKat-ok** [comment]
I also have this device
![IMG_20230529_193642](https://github.com/Kobo-InkBox/inkbox/assets/78702592/71795287-6328-4d28-be87-b4d1a2f6bc65)
![IMG_20230529_193701](https://github.com/Kobo-InkBox/inkbox/assets/78702592/34159f1b-20bd-4a60-b596-d87e1b470133)
![IMG_20230529_193706](https://github.com/Kobo-InkBox/inkbox/assets/78702592/2aae694e-daa9-4589-a05e-e5609ea0aba6)
![IMG_20230529_193718](https://github.com/Kobo-InkBox/inkbox/assets/78702592/8c39c079-1884-4265-95a3-049a82bebd46)
![IMG_20230529_193729](https://github.com/Kobo-InkBox/inkbox/assets/78702592/08ea8868-867b-4569-8400-f2f0eee4211b)
![IMG_20230529_193742](https://github.com/Kobo-InkBox/inkbox/assets/78702592/524b34a7-c122-4255-9729-11aa108e80ef)
![IMG_20230529_193748](https://github.com/Kobo-InkBox/inkbox/assets/78702592/772e2760-fe44-4637-809f-17c6684ac86d)
![IMG_20230529_193811](https://github.com/Kobo-InkBox/inkbox/assets/78702592/4b6ba262-cd4b-4789-85b7-5f4fee3f28d2)
![PICT0001](https://github.com/Kobo-InkBox/inkbox/assets/78702592/00cffd18-63de-4d14-8b1e-130fa443ae88)
![PICT0002](https://github.com/Kobo-InkBox/inkbox/assets/78702592/6d806323-152d-45d2-a8ec-337942ffd13a)
![PICT0003](https://github.com/Kobo-InkBox/inkbox/assets/78702592/fdcb865d-b178-4f25-92a3-c6a050a2e376)
![PICT0004](https://github.com/Kobo-InkBox/inkbox/assets/78702592/a78d2ee9-de1d-4313-86db-ebbcc8b266b8)
![PICT0005](https://github.com/Kobo-InkBox/inkbox/assets/78702592/2b1d7e31-5317-477c-bc4a-d2e16c02a427)
![PICT0006](https://github.com/Kobo-InkBox/inkbox/assets/78702592/9793c9de-bce4-44c8-aaf2-78d412328822)
![PICT0007](https://github.com/Kobo-InkBox/inkbox/assets/78702592/5dbb975c-5831-4fae-a03f-59a5efe9d660)

**Comment by kajusK** [comment]
Same problem here, the serial number ends with 4C1.  Is there something I can do to help with debugging this? I have some Linux + embedded software background, so if you point me to a direction to look, I can help a bit.

**Comment by Szybet** [comment]
Oh and as for help you are offering: Your model has been luckely ported already as I mentioned, but you are welcome to contribute to the project in other ways :smiley:

**Comment by ciprianopagano-png** [comment]
Hi i've an issue to install quill os, now my screen is white and want budge :/ any help ? 
my is kobo nia n306 but not the model n306c.
