### ISSUE TITLE
Can't find `inkbox.ddns.net`

### ISSUE THREAD

**Issue by QazCetelic** [Kobo-InkBox/inkbox#48]
It seems like the URL linked to the GitHub project does not point to an active site

![image](https://user-images.githubusercontent.com/51381523/233800044-58650017-f3d5-44ac-bbc5-fe930ada0c48.png)

**Comment by tux-linux** [comment]
Huh?

**Comment by tux-linux** [comment]
Confirmed no-ip again. Should be working within 30m

**Comment by Szybet** [comment]
( Use wayback machine if needed )
