### ISSUE TITLE
Minor: any suggestions on email client?

### ISSUE THREAD

**Issue by abawany** [Kobo-InkBox/inkbox#51]
I was wondering if someone has considered adding an email client to the official list of apps or has any suggestions on how to start with adding one? I'm guessing Thunderbird is going to be too heavy so I was thinking of something more basic or even a shell-based one (e.g. mutt or aerc-email.org.)

**Comment by Szybet** [comment]
Could certainly be added. I don't have any interest of doing it, but I can help.
The easiest path would be finding a email client written in C++ & Qt 5, Kuratius on discord found this list:
https://en.wikipedia.org/wiki/Category:Email_clients_that_use_Qt 

And then well porting it, some links and guides:
https://inkbox.ddns.net/wiki/index.php?title=InkBox_GUI_user_apps
https://github.com/Szybet/niAudio/tree/main/apps-on-kobo
https://github.com/Szybet/niAudio/blob/main/apps-on-kobo/qt-setup.md
You can also look how other user apps are made. The ones i created have an automated script.

If you want faster help, you can join our matrix or discord server

**Comment by abawany** [comment]
I'm now running Inkbox on a Kobo N437 and will start looking at Kontact from the above list since it seems to be still getting updates.

**Comment by tux-linux** [comment]
Good luck; compiling KDE Qt apps is often a nightmare (ask @Szybet)
Join the Discord or Matrix if you need help

**Comment by abawany** [comment]
Thanks, I've joined the matrix channels and will ask for help there once I've setup an environment.
