### ISSUE TITLE
List of supported devices?

### ISSUE THREAD

**Issue by locness3** [Kobo-InkBox/inkbox#53]
Is there any list of supported devices somewhere?

**Comment by tux-linux** [comment]
![image](https://github.com/Kobo-InkBox/inkbox/assets/63172576/f4b6594a-87f3-4684-9b11-6eb826ae9473)
https://inkbox.ddns.net/downloads.html

**Comment by locness3** [comment]
Oh, thank you! Sorry for stupid issue.

**Comment by tux-linux** [comment]
No problem !
