### ISSUE TITLE
Is there any way to cleanly install InkBox on Kindle devices empty memory?

### ISSUE THREAD

**Issue by GMGuimaraes** [Kobo-InkBox/inkbox#55]
My kindle paperwhite 10th generation had a factory problem where its internal memory was corrupted even though the device worked. But when connecting via usb on the desktop to pass books, it occurred as a pen drive with the same problem and windows asked to format it. After that, the device is in an eternal boot loop.
So I'd like to know if there's a way to install InkBox without needing the Jailbreak steps with the existing OS for those specific cases like mine, because unlike a computer where I can reinstall the original system or another, on kindle I didn't find anything that comes even close to that, and searching for solution I found InkBox  alternative.
I see that you are working hard on the Kobo system and also have plans for the Kindle, and the fact that there is no fix for these devices makes your OS revive countless devices considered dead.
The closest thing I could find besides Inkbox was Koreader, which is more in line with the solution I'm looking for is you because the other alternative does not consider formatted memory, being just a modification of the existing product and not the installation of a new OS.

**Comment by Szybet** [comment]
It would be possible if someone ported Inkbox to this device and the Kindle was not locked up, i'm not sure about this model.
So in short, nope

**Comment by Kuratius** [comment]
I've seen a screenshot according to which there is an exposed serial contact (but requires soldering!) between the screen and the pcb on a voyage, there is a chance you can do something with but I wouldnt count on it. At the very least it might give a hint as to what is going wrong with the bootloop.
