### ISSUE TITLE
Kobo Glo N613 no wifi  and no update from 1.9 to 2.0

### ISSUE THREAD

**Issue by Trilla77** [Kobo-InkBox/inkbox#58]
Hello,
as I read about Inkbox first some days ago I did a quick install and I find eveything very nice. Only the wlan adapter is missing.
If I install the package Ihk 2.0 in the top of the screen there is a wifi symbol. But in interaction no wlan was found and the logs say something like adapter is missing.

If I start with Inkbox 1.5 and update Step by Step everything seems fine. But in all updates the wifi symbol is missing. From 1.5 up to 1.9. Also the updating process from 1.9 to 2.0 is not possible. Message shows wrong signature.
Did someone have a working N613 with wifi?
Probably, Is there a way to connect to kobo with putty and usb port? Then I could try to figure out, where the problem could be.

**Comment by Szybet** [comment]
Glo wifi was added in 2.0

You can't upgrade from 1.9 to 2.0, you need to flash an image

To get into the shell without wifi, look here:
https://github.com/Kobo-InkBox/rootfs/issues/8

**Comment by Szybet** [comment]
Checked it, works for me on my n613 machine, so i can't help
you need to manually look at /usr/local/bin/wifi/ scripts
