### ISSUE TITLE
Anki support?

### ISSUE THREAD

**Issue by them1ghtydill** [Kobo-InkBox/inkbox#6]
I found a popular flashcard app called Anki (https://github.com/ankitects/anki). It runs on Qt, and from what I've read, it should not be too hard to compile and run Anki on an InkBox device. I am willing to compile Anki on my Pi 4, but unfortunately I have misplaced my Kobo Mini so I wouldn't be able to test it... 
Thanks.

**Comment by tux-linux** [comment]
Maybe...?
Seems like there's Python and Rust in the party too, will probably make
things harder...

**Comment by Szybet** [comment]
Anki is hard to compile even on x86_64 becouse of cpp, python and rust.
The app also has too many features that would not work on a ereader.
I will make a miniature version of anki in rust in the ( not near ) future with kobo ereaders in mind

**Comment by Szybet** [comment]
[https://github.com/Szybet/sanki](https://github.com/Szybet/sanki)

Depending how hard will it be to setup QT for kobo, and sql database reading a very basic version could be ready in a month
