### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by marzagheddon** [Kobo-InkBox/inkbox#64]
Is it possbile to have ReadiumLCP supported? https://www.edrlab.org/readium-lcp/

**Comment by Szybet** [comment]
This project is not so advanced to think about such things - ~~go to the koreader project, they could be interested~~

> Any trusted organization can develop an LCP compliant Reading System, and any trusted organization can setup an LCP compliant distribution solution. Trusted here means that the developer will need to show that he is working for an established organization in the publishing industry and we can safely provide him with confidential information about LCP.

> There is still a constraint to the implementation of LCP: in order to guarantee the interoperability of the different LCP servers and reading apps which constitute the “LCP network”, any implementation (either client-side in a Reading System, or server-side in a distribution solution) must be certified by EDRLab (as Certification Authority) before it is deployed.

This is a closed source solution, they would never allow open code to support it - it would no longer be "safe"...

**Comment by tux-linux** [comment]
I am sorry; although it seems like a great framework, we won't integrate closed-source software in an open-source project.
