### ISSUE TITLE
Kobo Glo HD N437 - No browser?

### ISSUE THREAD

**Issue by jandebleser** [Kobo-InkBox/inkbox#67]
Hi, 
First of all, thanks for the great work. It looks really impressive.
I want to use my kobo as an interactive dashboard for home assistant, but I'm unable to find the browser. 
I can see in the youtube clips you can launch it from the "Build-in apps" menu, but netsurf, nor Kobox appears there.
Am I missing something?

I'm running the image 

    fb5f083b3c2c878bb66cf7a732e6dc4d9fc68707e9a6bf5efc1e43b2d0b3ece5  inkbox-2.0-n437.xz

![20240212_190422](https://github.com/Kobo-InkBox/inkbox/assets/957494/746581fc-3493-476b-8699-c996543d3283)

Thanks!

**Comment by Szybet** [comment]
enable kobox in settings
also you can install midori browser I think

Those are old browser, barely supporting js

Xorg is buggy and experimental, Don't expect much. 

A better solution would be to port a Qt5 & C++ app dashboard, maybe it exists?

**Comment by Szybet** [comment]
maybe kobos is not supported on this device to the point it was disabled
maybe
I propose you either wait for @tux-linux to answer or you root the device, and look into the code to know what's going on

**Comment by tux-linux** [comment]
Please go into settings and generate a system report (2nd page)
Then send the pdf that will be in your onboard storage
Thanks!

**Comment by jandebleser** [comment]
[sysreport-2024-02-12_12.31.06.pdf](https://github.com/Kobo-InkBox/inkbox/files/14251348/sysreport-2024-02-12_12.31.06.pdf)

**Comment by Szybet** [comment]
Woah this looks bad. Try to reboot. If this wont work, root the device and enabke on screen boot logging, there is a flag for it

**Comment by tux-linux** [comment]
On-screen boot also works for non-root devices. You can enable it by writing true to [p1]/flags/BOOT_USB_DEBUG
P1 is preferably mountable with Linux (ext4)

**Comment by jandebleser** [comment]
The BOOT_USB_DEBUG flag did not change anything, but I put the DISPLAY_DEBUG flag and I got this output:
![20240213_100539](https://github.com/Kobo-InkBox/inkbox/assets/957494/d1fdf609-870d-44d0-a1af-deb7379e5455)

    Kobox base rootfs package's signature is invalid! Aborting launch...

**Comment by jandebleser** [comment]
The flags [here](https://inkbox.ddns.net/wiki/index.php?title=Boot_flags) talk about a "root kernel" (=rooted kernel?). However, I can find any info on how to root the device.

**Comment by Szybet** [comment]
> The BOOT_USB_DEBUG flag did not change anything, but I put the DISPLAY_DEBUG flag and I got this output:
> ![20240213_100539](https://github.com/Kobo-InkBox/inkbox/assets/957494/d1fdf609-870d-44d0-a1af-deb7379e5455)
> 
>     Kobox base rootfs package's signature is invalid! Aborting launch...
> 
> 

Reflash the image

**Comment by jandebleser** [comment]
Reflashing the SD card fixed the issue!
I still cannot find anything about routing the kernel on the wiki. Do you have a link I can follow.
Thanks for your support!

**Comment by Szybet** [comment]
https://github.com/Kobo-InkBox/inkbox/wiki/How-to-root-the-device-and-how-to-connect-to-WiFi-using-USBNET-or-ITERM-CLI

**Comment by jandebleser** [comment]
Ah ok! I was looking at the other wiki. 
Thanks!
