### ISSUE TITLE
InkBox not starting after flashing 1.5 image

### ISSUE THREAD

**Issue by them1ghtydill** [Kobo-InkBox/inkbox#7]
Flashed the 1.5 image to the Mini and the Kobo turns on. I see 'InkBox' but the green light keeps endlessly flashing. Problem?

**Comment by tux-linux** [comment]
`sync` the SD card before getting it out. Or maybe a corrupted SD or
corrupted download. This image has been tested and works. I would need
serial output to debug further.
TL;DR Reflash the SD or use a new one.
